powsybl/powsybl-metrix

.github/workflows/maven.yml

N/A
Continuous integration
The sonar analysis fails because java 8 is considered as deprecated by sonar
Update the JDK version in the CI to Java 11
(if any of the …

Update java version to v11

---

metrix-mapping/pom.xml

Signed-off-by: Paul Bui-Quang <paul.buiquang@rte-france.com>
Cleanup
Duplicate dependency in pom
Remove the duplicate dependency

Remove duplicate dependency in pom

---

.github/workflows/ci.yml
.github/workflows/qa_pr_cpp.yml
metrix-simulator/cmake/CodeCoverage.cmake

Due to github virtual environment of ubuntu-latest image upgraded to Ubuntu 20, compiler and gcov versions are updated. g++-8 and gcov-8 are no longer available so we use the newer default version (gcc 9 and gcov 9)

Update github actions

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/Metrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixNetwork.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariableProvider.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/compatibility/CsvResultListener.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/io/ResultListener.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/remedials/Remedial.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/remedials/RemedialReader.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixMock.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/remedials/RemedialReaderTest.java
metrix-integration/src/test/resources/remedial.txt
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/MappingLimitType.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesConstants.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMapper.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/json/JsonFieldName.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/OtherVariable.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/OtherVariableProvider.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigToJsonTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesProvideTsTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/json/TimeSeriesMappingJsonTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStoreTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java

Signed-off-by: berthault <valentinberthault@outlook.fr>
refactorisation
no change

[IMG-586] Adding Remedial Object

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/DefaultNetworkSourceImpl.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/Metrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/NetworkSource.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/io/MetrixConfigResult.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysisResult.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/remedials/RemedialReader.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixAnalysisTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixMock.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/remedials/RemedialReaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/CalculatedTimeseriesStoreTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java
metrix-tools/src/test/java/com/powsybl/metrix/tools/CommandLineMock.java

Signed-off-by: berthaultval <valentinberthault@outlook.fr>
refactorisation
no change

[IMG-607] Add analysis of Metrix Configuration

---

metrix-integration/pom.xml
metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/Metrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixAppLogger.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunk.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunkLogger.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixConfig.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixDslData.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixNetwork.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixSubset.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantProvider.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixToolLogger.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariantProvider.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariantReaderImpl.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputData.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputDataGenerator.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixOutputData.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixChunkParam.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/timeseries/InitOptimizedTimeSeriesWriter.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixConstantVariantTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputDataGeneratorTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixRunResultTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantsProviderTest.java
metrix-tools/pom.xml

feature
allow metrix input extraction

[IMG-506] Retrieving Metrix input files on opt interface

---

.github/workflows/ci.yml
.github/workflows/qa_pr_cpp.yml

Use gcovr from apt instead of pip #34

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java

[IMG-1111] - Move actions to workers

---

metrix-integration/src/main/groovy/com/powsybl/metrix/integration/MetrixDslDataLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java

[IMG-1072] - Directional threshold when EndOr is in separated block

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixDataName.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java

[IMG-1228] MMA export of all time series

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantProvider.java

[IMG-1390] network extraction correction

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputDataGenerator.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputDataGeneratorTest.java

[IMG-1257] remove HADES_DIR environment variable

---

metrix-integration/pom.xml
metrix-integration/src/main/groovy/com/powsybl/metrix/integration/MetrixDslDataLoader.groovy
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixNetwork.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariantReaderImpl.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputData.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixVariantsWriterTest.java
metrix-mapping/pom.xml
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkPointWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigCsvWriter.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/AbstractCompareTxt.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkPointWriterTest.java
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0100
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0200
pom.xml

powsyblcore 4.7.0

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java

[FIX] Correction forkjoin pool classloader

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java

[IMG-1299] timeSeriesExists optimisation

---

metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkPointWriterTest.java

NetworkPointWriterTest correction

---

metrix-integration/src/main/groovy/com/powsybl/metrix/integration/MetrixDslDataLoader.groovy
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderTest.java
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/LogDslLoader.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesProvideTsTest.java

[IMG-1068] add type to script println

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/exceptions/ContingenciesScriptLoadingException.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixInputAnalysis.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixExceptionTest.java

[IMG-1175] specific exception for contingencies script evaluation

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/utils/LocalThreadExecutor.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/LocalThreadExecutorTest.java

[IMG-1501] execute job in local thread

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/ChunkCutter.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/Metrix.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/ChunkCutterTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixMock.java

[IMG-1304] Avoid launching useless computations

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixDslData.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java

[IMG-476] Observation thresholds overwritten by monitoring thresholds

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputData.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/io/MetrixDie.java
metrix-integration/src/test/resources/simpleNetwork.json
metrix-integration/src/test/resources/simpleNetworkDefault.json
toto

[IMG-301] remove binary inputs generation for metrix network

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/OtherVariable.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigToJsonTest.java

[IMG-184] Recovery of lost mapping config serialization test

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixInputAnalysis.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixRemedialAnalysisTest.java

[IMG-1062] remedial with zero action number is valid

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixConfig.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixParameters.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/MappingParameters.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkPointWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/common/MetrixIidmConfiguration.java
pom.xml

[IMG-1644] update powsybl-core version to 4.10.1

---

metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderTest.java
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/LogDslLoader.groovy
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java

[IMG-1561] Adding line separtor for writeLog binding

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/metrix/MetrixAnalysis.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/InitOptimizedTimeSeriesWriterTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixConstantVariantTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantsProviderTest.java
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/DataTableDslLoader.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/AttributeNameToValue.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/DataTable.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/DataTableStore.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/exception/DataTableException.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/BalanceSummaryTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentTimeSeriesWriterTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkPointWriterTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifierTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapToTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperCheckerTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesProviderTsTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java

[IMG-1735] DataTable using in mapping script

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/DefaultEquipmentTimeSeriesMapperObserver.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/EquipmentTimeSeriesMapperObserver.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/MappingKeyNetworkValue.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkPointWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigChecker.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentTimeSeriesMapperObserverTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/MappingKeyNetworkValueTest.java

[IMG-304] Not mapped equipment timeseries

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/EquipmentGroupTsData.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/EquipmentGroupType.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/GeneratorGroupTsData.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/LoadGroupTsData.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/SimpleEquipmentGroupType.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/EquipmentGroupTimeSeriesMapperObserver.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfig.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigEquipmentCsvWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigJson.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigLoader.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/json/JsonFieldName.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentGroupTimeSeriesMapperObserverTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigToJsonTest.java

[IMG-1685] By group equipment time series

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixConfig.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputDataGenerator.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixConfigTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputDataGeneratorTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-integration/src/test/resources/com/powsybl/config/test/config.yml
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/DefaultGenericMetadata.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigLoader.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TsMetadata.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java
metrix-tools/src/test/resources/com/powsybl/config/test/config.yml

[IMG-1532] Imagrid integration

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/EquipmentGroupTsData.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/GeneratorGroupTsData.groovy
metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/LoadGroupTsData.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigLoader.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentGroupTimeSeriesMapperObserverTest.java

[IMG-1685] Power type is not taken into account when its value is false

---

metrix-integration/pom.xml
metrix-integration/src/main/java/com/powsybl/metrix/integration/DefaultNetworkSourceImpl.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunkLogger.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixConfig.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixDslData.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixHvdcControlType.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixHvdcRegulationType.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixParameters.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixPtcControlType.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixOutputData.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixConstantVariantTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixVariantsWriterTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/io/MetrixDieTest.java
metrix-mapping/pom.xml
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/GeneratorBoundLimitBuilder.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMapperChecker.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigCsvWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesStoreUtil.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperCheckerTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesProviderTsTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesMetadataIndexTest.java
metrix-tools/pom.xml
metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixDieTool.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java
pom.xml

Upgrade powsybl core to v5.3.2

Upgrade powsybl core v5.3.2

---

metrix-integration/pom.xml
metrix-integration/src/main/java/com/powsybl/metrix/integration/DefaultNetworkSourceImpl.java
metrix-mapping/pom.xml
metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixDieTool.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java
pom.xml

[IMG-1924] Upgrade PowSyBl-core dependency to v5.0.0

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/EquipmentVariable.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapToTest.java

[IMG-1929] Missing default variable for mapToLines and mapToTransformers

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/DataTableDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/AttributeNameToValue.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/ContentFilter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/DataTable.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/QueryFilter.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/AbstractCompareTxt.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/DataTableDslLoaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/DataTableTest.java

[IMG-1951] Pouvoir filtrer et rechercher une valeur

---

metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/EquipmentVariable.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/MappableEquipmentType.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigLoader.java

Remove deprecated mapToPsts

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

Prepare release 1.0.0

---

pom.xml

no
Bug fix
Release generation was blocked by groovydoc failing
groovydoc parameters are changed according to powsybl-parent documentation

Fix groovydoc generation

---

metrix-simulator/src/calculecrirecontraintesdodu.cpp
metrix-simulator/src/config/variant_configuration.h
metrix-simulator/src/reseau.cpp
metrix-simulator/src/reseau.h
metrix-simulator/tests_reference/connexite/composante_non_connexe/metrixOut.txt

Small changes were added to the random method in the v7.4.0, which shuffles the list of groups, so that the results are the same as the ones calculated through the internal v7.4.0.

V74 gpp11 correction

---

.github/workflows/ci.yml
.github/workflows/maven.yml
.github/workflows/qa_pr_cpp.yml
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariantReaderImpl.java
metrix-integration/src/main/java/com/powsybl/metrix/integration/remedials/RemedialReader.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMapper.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMapperChecker.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifierTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperCheckerTest.java
pom.xml

No
Feature
Powsybl-metrix is based on Java 11.
Powsybl-metrix is now based on Java 17.

Upgrade to java17

---

metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifierTest.java
pom.xml

No
Lib update
powsybl-core 5.3.2
powsybl-core 6.0.0

Upgrade powsybl-core to v6.0.0

---

.github/workflows/qa_pr_cpp.yml

No
Github workflow update
QA-PR-CPP pipeline is launched when PR are opened or synchronized but also edited/commented/...
QA-PR-CPP pipeline is launched only when PR is opened or synchronized
No

delete "edited" from triggers

---

.github/workflows/ci_centos7.yml
.github/workflows/ci_ubuntu.yml
.github/workflows/maven_ubuntu.yml
.github/workflows/qa_pr_cpp_centos7.yml
.github/workflows/qa_pr_cpp_ubuntu.yml
metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

Auto upload assets

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

Tmp prepare release v2 0

---

pom.xml

dependency security update
Direct vulnerabilities:
[CVE-2023-6378](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-6378)
Vulnerabilities from dependencies:
[CVE-2023-6378](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-6378)
[CVE-2022-23307](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23307)
[CVE-2022-23305](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23305)
[CVE-2022-23302](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23302)
[CVE-2021-4104](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4104) …

Bump logback to 1.4.14

---

.github/workflows/qa_pr_cpp_centos7.yml
pom.xml

No
Bug fix
Jacoco reports were not aggregated properly so SonarCloud was showing false failing results
Jacoco reports are properly aggregated
For now, the aggregated report is in metrix-tools, it can be interesting to move it to metrix-distribution.

Change Jacoco settings for consolidated reports

---

.github/workflows/maven_ubuntu.yml
metrix-distribution/pom.xml
metrix-tools/pom.xml
pom.xml

No
Bug fix
Jacoco reports were aggregated in metrix-tools directory but onyle for the other modules so metrix-tools coverage reports were not used in sonarcloud analysis.
Reports are now aggregated in metrix-distribution, like it is done in powsybl-core

Fix CI and jacoco config

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/Metrix.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/InitOptimizedTimeSeriesWriterTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixAnalysisTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixContingencyAnalysisTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixExceptionTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixInputTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixRemedialAnalysisTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixRunResultTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantsProviderTest.java
metrix-mapping/pom.xml
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkPointWriter.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/common/MetrixIidmConfiguration.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/BalanceSummaryTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentGroupTimeSeriesMapperObserverTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentTimeSeriesMapperObserverTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/EquipmentTimeSeriesWriterTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/MappingKeyNetworkValueTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkPointWriterTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifierTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapToTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperCheckerTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesProviderTsTest.java
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0100
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0200
pom.xml

Update to powsybl 6.1

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

No
Release preparing
powsybl-metrix is in v2.1.0-SNAPSHOT
powsybl-metrix is in v2.2.0-SNAPSHOT
**Do NOT squash the commits**

Prepare release v2.1.0

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifier.java
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0100
metrix-mapping/src/test/resources/expected/NetworkPointWriter/SimpleNetworkWithReducedThresholds_1_20150101_0200
pom.xml

No
Dependency upgrade
powsybl-core 6.1 was used
powsybl-core 6.2 is now used

Update powsybl-core to 6.2.0

---

pom.xml

No
Feature
Parent used is v17
Parent used is now v18: it allows to delete some lines of configuration used to generate the groovydoc, we now use a parameter added in the parent.

Update project parent to powsybl-parent v18

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/InMemoryTimeSeriesStore.java
pom.xml

No
Feature
Metrix used powsybl-core 6.2.x
Metrix now uses powsybl-core  6.3.0

Bump powsybl-core dependency to 6.3.0

---

README.md
metrix-integration/src/main/java/com/powsybl/metrix/integration/compatibility/CsvResultListener.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeSeriesStore.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigTableLoaderTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeSeriesStoreTest.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesStoreUtilsTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MetrixTool.java

No
Naming issue
Class was named FileSystemTimeseriesStore.
Class is now named FileSystemTimeSeriesStore to be consistent with other classes.
The class `FileSystemTimeseriesStore` has been renamed `FileSystemTimeSeriesStore`.

Fix FileSystemTimeSeriesStore class name

---

.github/workflows/ci_centos7.yml
.github/workflows/ci_ol8.yml
.github/workflows/ci_ubuntu.yml
.github/workflows/maven_ubuntu.yml
.github/workflows/qa_pr_cpp_centos7.yml
.github/workflows/qa_pr_cpp_ol8.yml
.github/workflows/qa_pr_cpp_ubuntu.yml

No
CI improvement
The CI runs on Ubuntu-latest and on CentOS7.
The GitHub actions runs on node16.
The CI now also runs on Oracle Linux 8.
The GitHub actions now runs on Node20, except on CentOS7 since the OS is not compatible with Node20.

Creation of the CI on Oracle Linux 8 and update of Github actions

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

No
Release preparing
powsybl-metrix is in v2.3.0-SNAPSHOT
powsybl-metrix is in v2.4.0-SNAPSHOT
**Do NOT squash the commits**

Prepare release v2.3.0

---

pom.xml

Update powsyybl-core to v6.4.1

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeSeriesStore.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeSeriesStoreTest.java

No
Bug fix
When using `importTimeSeries(List<TimeSeries> timeSeriesList, int version, ExistingFilePolicy existingFilePolicy)`, it threw an exception if TimeSeries had the same index, even if their chunks had values on different index values (given by different offsets + index of the values list in the chunk). That created exceptions when using itools since TimeSeries are often divided into multiple chunks after being computed by metrix-simulator.
When using `importTimeSeries(List<TimeSeries> timeSeriesList, int version, …

Fix appendTimeSeries for TimeSeries with the same index but different chunks

---

README.md

No
Docs update
Readme.md refers to deleted documentation on powsybl.org.
Replace with links to the new readthedocs website.

Documentation: Fix dead links in readme.md

---

docs/mapping.md

No
Documentation
Metrix mapping module: Better documentation of transformers mapping (including tap changers)

Improve transformers mapping documentation

---

.github/workflows/maven.yml
.mvn/wrapper/maven-wrapper.properties
README.md
metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java
metrix-tools/src/test/java/com/powsybl/metrix/tools/AbstractToolTest.java
metrix-tools/src/test/java/com/powsybl/metrix/tools/MappingToolTest.java
metrix-tools/src/test/java/com/powsybl/metrix/tools/MetrixDieToolTest.java
metrix-tools/src/test/java/com/powsybl/metrix/tools/MetrixToolTest.java
mvnw
mvnw.cmd

No
Feature / Bugfix
maven test fails on windows due to line end character in test.
* Added Java CI build for Windows and MacOS - also added Maven wrapper
* test passing on windows, and consistent with other tests.
* fixed also some typos on readme
* some minor code improvements
* fixed in itools command description typo time serie -> time serie**s**

Add maven wrapper, add Windows and MacOS CI Java build 

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

Prepare release v2.4.0

---

metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixTimeSeriesVariantProvider.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/NetworkPointWriterTest.java
metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java
pom.xml

No
powsybl-core 6.4.1 was used
powsybl-core 6.5.0 is now used

Update powsybl-core to v6.5.0

---

docs/conf.py
docs/mapping.md
docs/metrix.md
install.sh
metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixConfig.java
metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixConfigTest.java
metrix-mapping/src/main/java/com/powsybl/metrix/mapping/common/MetrixIidmConfiguration.java
metrix-mapping/src/test/java/com/powsybl/metrix/mapping/common/MetrixIidmConfigurationTest.java

No
Feature / Usability
Annoying mandatory and undocumented `command` Metrix module parameter.
All parameters and even the Metrix module configuration itself is optional, with reasonable defaults.
Doc update

Default metrix module config

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

_**DO NOT SQUASH-MERGE THIS PR**_
No
Release

Prepare release v2.5.0

---

.github/workflows/full-ci.yml
README.md

Fix full-ci Clang Tidy

---

.github/workflows/release-ci.yml

No
Bug fix
Ci ran only on release creation, which does not work when writing a draft and then releasing
CI run on release publishing

Fix release CI

---

README.md

No
Doc update
There is a link to a Spectrum community but it's not used anymore
The link is removed

Remove link to spectrum in README

---

metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkTopographyChangeNotifier.java
pom.xml

Update powsyblcore dependency to v6.6.0

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

**DO NOT MERGE ON GITHUB**
No
Release preparation

Prepare release v2.6.0

---

.github/workflows/snapshot-ci.yml

Reduce Slack messages for successful builds

---

.github/workflows/snapshot-ci.yml

No
Bugfix
Failure in build is not detected
Failures are now detected

Fix failure detection in snapshot CI

---

metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

:warning: **DO NOT MERGE ON GITHUB**
No
Release
v2.7.0-SNAPSHOT
v2.7.0

Prepare release v2.7.0

---

.github/workflows/dev-ci.yml
.github/workflows/fork-build-tests.yml
.github/workflows/fork-sonar.yml

Same as https://github.com/powsybl/powsybl-core/pull/3451
**Other information**
Artifacts upload are still managed by the "Dev CI" workflow, even for external PRs.

Add CI for PRs from forks

---

.github/workflows/dev-ci.yml

No
Bug fix
git fetch fails on forks
Split the fetch commands to address cross-repository pull requests. This ensures proper retrieval of head references from forked repositories. Improves compatibility and stability of the CI pipeline.

Optimize git fetch strategy for pull request workflows

---

.github/workflows/fork-build-tests.yml

No
Bug fix
The `if: matrix.os == 'ubuntu-latest'` condition is never true since matrix is not defined in this workflow, therefore artifacts are not build nor uploaded
The condition is removed and the artifacts are uploaded

Remove condition in generation of CI artifact for C++ analysis

---

.github/workflows/fork-sonar.yml

No
Bug fix
Copy of build directory fails during the CI
Copy of the build directory now works properly

Fix copy of extracted build directory

---

metrix-distribution/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

No
- Uses powsybl-core 6.8.0-RC2 and powsybl-parent 20 
- Old dependencies
- Uses powsybl-core **6.8.0** and powsybl-parent **20.2**
- Upgraded several dependency versions, including Guava, AssertJ, JUnit, and SLF4J, to their latest stable releases. Improved consistency by centralizing dependency management for `log4j-over-slf4j`.
**What changes might users need to make in their …

Update powsybl-core to 6.8.0 and other dependencies versions

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

No
update
Builds fail on macOS-15 when using maven wrapper v3.2.0
```
Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised.
Investigate or delete /Users/runner/work/powsybl-core/powsybl-core/.mvn/wrapper/maven-wrapper.jar to attempt a clean download.
If you updated your Maven version, you need to update the specified wrapperSha256Sum property.
Error: Process completed with exit code 1.
```
Maven wrapper is updated to v3.3.3 and the builds work
**Does this PR introduce a breaking change or deprecate …

Update maven wrapper

---

.github/workflows/dev-ci.yml
.github/workflows/fork-build-tests.yml
.github/workflows/fork-sonar.yml
.github/workflows/full-ci.yml
.github/workflows/release-ci.yml
.github/workflows/snapshot-ci.yml
metrix-distribution/pom.xml
metrix-integration/pom.xml
metrix-mapping/pom.xml
metrix-tools/pom.xml
pom.xml

No
Java 17 is used
Java 21 is used
PowSyBl-Metrix now only supports Java 21 and higher. Please check that your installed SDK is still compatible. If you are using Ubuntu 20.04 LTS and the preinstalled Maven version, you will need to upgrade your Maven version too at least up to a version …

Migrate to Java 21
