- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigCsvWriter.java
Fix a crash when mapping on a network that has boundary lines. When doing so, an exception gets thrown:
`
java.lang.AssertionError: Unsupported equipment type BoundaryLine
at com.powsybl.metrix.mapping.TimeSeriesMappingConfigCsvWriter.writeEquipment
...
`
This fix allows the writer to take boundary lines into account when producing output.
Crash when mapping on a network with boundary lines.
No more crash. Now boundary …
> Fix crash when mapping on networks with unresolved boundary lines

- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixInputData.java
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixNetwork.java
Signed-off-by: Paul Bui-Quang <paul.buiquang@rte-france.com>
Bug fix
Since https://github.com/powsybl/powsybl-core/pull/925 there is new contingency types that are not handled by MetrixInputData
Handle this new types
> Fix metrix input data for new contingency types

- metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
Signed-off-by: berthault <valentinberthault@outlook.fr>
Bug fix
When generating the load chronicles of the works in the METRIX postprocessings (basecaseLoad and OutageLoad) and the resulting summary statistics, the fact of using directional thresholds leads to having chronicles in absolute value.
This is not the case when there are no directional thresholds and this sign information is useful for analysis.
Keep the sign …
> [IMG-588] Alignment on directional thresholds

- metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
- metrix-integration/src/main/java/com/powsybl/metrix/integration/io/MetrixConfigResult.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixMock.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixTest.java
Signed-off-by: berthault <valentinberthault@outlook.fr>
Bug fix
If chronicles are created during the METRIX configuration, they cannot be retrieved in output
If chronicles are created during the METRIX configuration, they must be able to be retrieved on output.
> [IMG-432]add access to chronicles created in metrix configuration script

- metrix-integration/pom.xml
- metrix-integration/src/main/java-templates/com/powsybl/metrix/tools/PowsyblMetrixVersion.java
> [IMG-1532] add powsybl-metrix Version AutoService

- pom.xml
No
Add gmavenplus-plugin config in pom in order to generate javadoc
Groovydoc/javadoc is not generated nor sent to sonatype
doc is sent
> Add gmavenplus-plugin config in pom in order to generate javadoc

- metrix-simulator/external/CMakeLists.txt
No
It changes the way the library SuiteSparse is downloaded.
SuiteSparse was previously downloaded directly from its historical website.
SuiteSparse is now downloaded from its official Github repository.
No
> Changed SuiteSParse source for Devin

- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesStoreUtil.java
Quality
Methods addAll may be called on Collections.emptyList() which is immutable
Collections.emptyList() replaced by new ArrayList<>()
> Java:S6322: unsupported methods should not be called on some collection implementations

- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixChunk.java
> Network extraction impossible when network id contains brackets (or other problematic characters)

- metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
No
Bug fix
The methods `getStaticStars` and `createCompilerConfig` were declared static during Java 17 upgrade but it makes impossible to override those methods, which can be useful for users wanting to extend the class `TimeSeriesDslLoader`.
The two methods are not anymore static and a new variable (`equipmentGroupTypes`) is used to specify the class declaring the enum listing the equipment group types.
**If yes, please check if the following requirements are …
> Fix method that should not be static

- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStoreTest.java
- metrix-mapping/src/test/resources/timeseries.json
No
Bug fix
The first issue is that a wrong exception is thrown if the path provided during FileSystemTimeseriesStore creation is not a directory.
During a call to `getTimeSeries()`, the returned Optional can not be empty:
- If a TimeSeries of the wrong subClass (`DoubleTimeSeries` or `StringTimeSeries`) is found, an exception is thrown
- If multiple TimeSeries of the right subClass are found, an exception is thrown
- If a single TimeSeries of the right subClass is found, it is returned in an Optional
The expected exception is now …
> Fix FileSystemTimeseriesStore

- metrix-integration/src/main/java/com/powsybl/metrix/integration/compatibility/CsvResultListener.java
- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStore.java
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMappingConfigTableLoaderTest.java
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/FileSystemTimeseriesStoreTest.java
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/timeseries/TimeSeriesStoreUtilsTest.java
No
Bug fix
The current `importTimeSeries` method takes two booleans as parameters: `overwriteExisting` and `append`. However, an existing file cannot be overwritten (overwriteExisting` is only used with `append` to throw an exception when both booleans are false and a file already exists).
There is also no check that `overwriteExisting` and `append` cannot be true at the same time.
When a file already exists and `append` is true, the TimeSeriesIndex was not updated so only part of the chunks could be evaluated.
The chunks added were also not given an offset.
**What is the new behavior (if …
> Fix importTimeSeries method in FileSystemTimeseriesStore

- .github/workflows/ci_centos7.yml
- .github/workflows/qa_pr_cpp_centos7.yml
No
CI modification
The version of the action `dsaltares/fetch-gh-release-asset` used was the `master`. However, they just upgraded to Node20 in version `1.1.2`, which needs a version of a compiler not available on CentOS7.
The version used is now `1.1.1`.
> Fix action version in CentOS 7 CI

- metrix-mapping/src/main/groovy/com/powsybl/metrix/mapping/TimeSeriesDslLoader.groovy
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesDslLoaderTest.java
Feature
Statistics functions (sum, min, max, avg, median) used in groovy scripts on time series are computed by default on range/versions defined by the current computation.
The consequence is that results of computation using such functions are by default dependent on launched range/versions.
Statistics functions are computed by default on all existing steps/versions of time series.
**What changes …
> [IMG-2331] Statistics computation on all steps/versions by default

- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/TimeSeriesMapperChecker.java
- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/log/RangeLogPhaseTapPosition.java
- metrix-mapping/src/test/java/com/powsybl/metrix/mapping/TimeSeriesMapperCheckerTest.java
Feature
this feature is about groovy script mapToPhaseTapChangers usage on phaseTapPosition variable
if mapped phaseTapPosition value is outside steps interval, no mapping is done
if mapped phaseTapPosition value is outside steps interval, mapping is done with a corrected value
if mapped phaseTapPosition value is < lowTapPosition, mapping is done with lowTapPosition value
if mapped phaseTapPosition value is > highTapPosition, mapping is done with highTapPosition value …
> [IMG-2340] phaseTapPosition mapping outside the steps interval

- .github/workflows/ci_centos7.yml
- .github/workflows/qa_pr_cpp_centos7.yml
No
Temporary bug fix
- yum does not work anymore on CentOS container since the usual mirror has been discarded (CentOS has reached EOL)
- Node 16 is also deprecated
- Mirrors are changed
- Use of older Node versions is allowed now
Useful links:
- …
> Update CentOS CI due to CentOS EOL and Node 16 deprecation

- docs/metrix.md
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixComputationType.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixParametersTest.java
No
Feature
Metrix computation types are : OPF, LF, OPF_WITHOUT_REDISPATCHING
OPF_WITH_OVERLOAD computation type is added in order to obtain results even when all constraints cannot be resolved
> [IMG-2401] Add OPF_WITH_OVERLOAD computation type

- metrix-integration/src/main/java/com/powsybl/metrix/integration/dataGenerator/MetrixInputData.java
No
Bug fix
If the network used has a TwoWindingsTransformer with a PhaseTapChanger with lowTapPosition different than 0, powsybl-metrix will crash during `MetrixInputData.writeTwoWindingsTransformer` because it tries to get the step at a non-existing position (either lower than the lowTapPosition or higher than the maximum).
The export will now start at the lowTapPosition.
> Fix issue with TapPosition when lowTapPosition > 0

- metrix-mapping/src/main/java/com/powsybl/metrix/mapping/NetworkPointWriter.java
No
Bugfix
Poor performance of iidm export by mapping tool NetworkPointWriter
Expected iIDM export performance
Kudos @olperr1 helping me in the fix ❤️ 
on ENTSOE RealGrid (25MB), with 3 time points / 3 iIDM export:
- 2 minutes before fix
- 7 seconds after fix
> Fix mapping tool NetworkPointWriter iIDM export performance

- metrix-tools/src/main/java/com/powsybl/metrix/tools/MappingTool.java
- metrix-tools/src/test/java/com/powsybl/metrix/tools/MappingToolTest.java
No
Bugfix
mapping tool NetworkPointWriter uses the network ID in the file name.
IIDM export fails in case of special characters.
In particular CGMES files IDs are often in the form `urn:uuid:000....` and failing on Windows because of semicolon.
Illegal characters (OS dependent ...) are replaced by an underscore.
> Fix mapping tool iIDM export when network ID contains illegal characters

- docs/metrix.md
- metrix-integration/src/main/groovy/com/powsybl/metrix/integration/GeneratorData.groovy
- metrix-integration/src/main/groovy/com/powsybl/metrix/integration/LoadData.groovy
- metrix-integration/src/main/groovy/com/powsybl/metrix/integration/LossesData.groovy
- metrix-integration/src/main/groovy/com/powsybl/metrix/integration/MetrixDslDataLoader.groovy
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixVariable.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixDslDataLoaderDoctrineCostTest.java
Feature
In existing generator('id') configuration function, **redispatchingDownDoctrineCosts** and **redispatchingUpDoctrineCost** can be defined
In existing load('id') configuration function, **preventiveSheddingDoctrineCost** and **curativeSheddingDoctrineCost** can be defined
A new losses() configuration function is added with **costs** attribute.
These new attributes are defined with a value or a time series name.
**What changes might users need to make in …
> Adding doctrine costs configuration for redispatching, load shedding and losses

- .github/workflows/full-ci.yml
- .github/workflows/release-ci.yml
No
Bugfix
Same as #190 but for the other CIs
> Fix the other CentOS CI

- .github/workflows/snapshot-ci.yml
No
feature
Slack notification is sent on every CI launch
Slack notification in only sent if the CI fails or if it was activated manually
> Send Slack notification only on failure or on demand

- .github/workflows/dev-ci.yml
- .github/workflows/full-ci.yml
- .github/workflows/release-ci.yml
- .github/workflows/snapshot-ci.yml
No
CI update
Old github action versions
New versions are used
> Update GitHub actions

- metrix-integration/src/main/java/com/powsybl/metrix/integration/AbstractMetrix.java
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixGeneratorPostProcessingTimeSeries.java
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixLoadPostProcessingTimeSeries.java
- metrix-integration/src/main/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeries.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixGeneratorPostProcessingTimeSeriesTest.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixLoadPostProcessingTimeSeriesTest.java
- metrix-integration/src/test/java/com/powsybl/metrix/integration/MetrixPostProcessingTimeSeriesTest.java
Bug fix
Problem in finding equipment ids for which redispatching or load shedding metrix results exist when several identifiers start in the same way.
Example with ids 'CPNIE_ES_HY' and 'CPNIE_ES_HY_2B'
CPNIE_ES_HY_2B has redispatching results but CPNIE_ES_HY doesn't
The current behavior wrongly considers that 'CPNIE_ES_HY' has redispatching results too
**Other …
> Fix finding equipments id for which redispatching or load shedding metrix results exist
